# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Hyunwook Ko
title: 
email: keif247@gmail.com
website: Nooko92.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: 
github_username:  
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: 
linkedin_username: 
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: 
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
# about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  AI 엔지니어로 새로운 도약을 꿈꾸는 고현욱입니다. 과거에 코딩이 즐거웠던 기억과 AI의 잠재력에 대한 기대로 진로를 변경하게 되었습니다.


content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: middle
        title: 음악 추천 프로젝트  
        link: 
        # link_text: Project Website
        additional_links:
          # - title:  sproogen/modern-resume-theme
          #   icon: fab fa-github
          #   url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          시중에는 많은 음악추천 서비스들이 있지만, 대부분은 음악 자체를 분석해 추천(Content-based Recommendation)하기보다 비슷한 성향의 사용자에게 추천(Collaborative Filtering)하는 방식으로 진행됩니다. 저희 팀은 기존의 방식에 더해서 음악의 내용(멜로디, 화성 등)이 비슷한 음악을 추천하는 서비스를 제공하고자 프로젝트를 진행하게 되었습니다.
        - layout: middle
        title: 영화 추천 대회
        link: 
        # link_text: Project Website
        additional_links:
          # - title:  sproogen/modern-resume-theme
          #   icon: fab fa-github
          #   url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          
        - layout: top-middle
        title: Deep Knowledge Tracing 대회
        link: 
        # link_text: Project Website
        additional_links:
          # - title:  sproogen/modern-resume-theme
          #   icon: fab fa-github
          #   url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: middle
        # title: The Boring Company
        # link: boringcompany.com
        # link_text: boringcompany.com
        # sub_title: Senior Network System Administrator
        # caption: November 2017 - Present
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            아직 AI에서의 경력은 없습니다! 제 AI커리어의 시작을 함께할 회사를 찾습니다!

  - title: Technical Skill # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: middle
        # title: The Boring Company
        # link: boringcompany.com
        # link_text: boringcompany.com
        # sub_title: Senior Network System Administrator
        # caption: November 2017 - Present
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            <mark>Python</mark> <mark>Numpy</mark> <mark>Pandas</mark> <mark>PyTorch</mark> <mark>matplotlib</mark> <mark>Seaborn</mark> <mark>git</mark>
  
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Naver Boostcamp
        caption: 2022.09 ~ 2023.02
        sub_title: AI Tech - 추천 시스템
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          기초적인 DL과 추천 시스템의 다양한 모델들 배웠고 총 3번의 내부 대회와 최종 프로젝트를 수행했습니다.
      - layout: left
        title: UNIST M.S.
        caption: 2018.03 ~ 2020.02
        sub_title: 기계공학 (3.95/4.3)
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          MEMS(Micro Electro Mechanical System)를 이용한 생체 모사를 주로 연구했습니다.
      - layout: left
        title: UNIST B.S.
        caption: 2011.03 ~ 2018.02
        sub_title: 기계공학 (3.7/4.3)
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          기계공학의 기초 지식들을 배웠고 MATLAB을 사용한 경험이 있습니다.


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      취미 및 관심 분야:
      - 운동
      - 음악(듣기, 연주, 음악 이론)
      - 식도락

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
